import type { TypographyRole, TypographySettings } from '../theme-settings';

/* Font registry: the sole source of selectable values for ui.typography (a controlled enum; free-form font-family strings are not accepted).
   To add a custom font, add an entry to THEME_FONT_REGISTRY (the ThemeFontId type is derived automatically from the entry id):
   - subset-pipeline fonts require you to provide the woff2 and @font-face yourself (see the "Fonts and licensing" section of the README);
   - astro-fonts-api fonts only need provider + familyName and are downloaded and self-hosted automatically at build time.
   acquisition semantics:
   - subset-pipeline: self-hosted font; woff2 is generated by `npm run font:build` (pyftsubset content-aware subsetting), and @font-face is declared in global.css;
   - system: a pure system font stack with zero download;
   - astro-fonts-api: downloaded from the provider by the Astro Fonts API at build time and self-hosted; the page makes zero third-party requests. */

export type ThemeFontLocalVariant = {
  src: string;
  weight: number | string;
  style: 'normal' | 'italic';
};

type ThemeFontRegistryEntryBase = {
  id: string;
  label: string;
  /* Short name and source notes for the admin font cards: cardLabel + badge are shown on the card (badge is small light-gray text);
     label/sizeHint are registry metadata (full name and acquisition-cost notes) that the admin UI does not render directly today. */
  cardLabel: string;
  badge: string;
  roles: readonly TypographyRole[];
  /* fallbacks are stored verbatim as CSS literals (including quotes) so the default-role resolution matches the global.css tokens exactly. */
  fallbacks: readonly string[];
  license: string | null;
  sizeHint: string;
};

/* Union type discriminated by acquisition/provider: illegal combinations (such as astro-fonts-api + provider:null, or
   local without localVariants) fail to compile at `as const satisfies` and never silently reach the dropdown. */
export type ThemeFontRegistryEntry =
  | (ThemeFontRegistryEntryBase & {
      acquisition: 'system';
      provider: null;
      familyName: null;
      weights: readonly [];
    })
  | (ThemeFontRegistryEntryBase & {
      acquisition: 'subset-pipeline';
      provider: null;
      familyName: string;
      weights: readonly number[];
    })
  | (ThemeFontRegistryEntryBase & {
      acquisition: 'astro-fonts-api';
      provider: 'google' | 'fontsource';
      familyName: string;
      weights: readonly number[];
      /* Downloaded subsets for the remote provider; defaults to ['latin']. CJK entries must declare this explicitly (e.g.
         ['chinese-simplified', 'latin']), otherwise Chinese glyphs are absent from the output and silently fall back. */
      subsets?: readonly string[];
    })
  | (ThemeFontRegistryEntryBase & {
      acquisition: 'astro-fonts-api';
      provider: 'local';
      familyName: string;
      weights: readonly number[];
      /* Font file path (relative to the project root, e.g. './src/assets/fonts/xxx.woff2'). The build has zero network dependency,
         and the Astro Fonts API still generates the @font-face and metric-aligned fallback — the first choice for mainland-network or offline builds. */
      localVariants: readonly ThemeFontLocalVariant[];
    });

export type ThemeFontAcquisition = ThemeFontRegistryEntry['acquisition'];
export type ThemeFontProvider = ThemeFontRegistryEntry['provider'];

export const THEME_FONT_REGISTRY = [
  {
    id: 'noto-serif-sc',
    label: 'Noto Serif SC',
    cardLabel: 'Noto Serif SC',
    badge: 'Self-hosted subset',
    roles: ['readable', 'brand'],
    acquisition: 'subset-pipeline',
    provider: null,
    familyName: 'Noto Serif SC',
    fallbacks: ['ui-serif', 'Georgia', '"Times New Roman"', '"Songti SC"', 'serif'],
    weights: [400, 600],
    license: 'OFL-1.1',
    sizeHint: 'Self-hosted content subset'
  },
  {
    id: 'lxgw-wenkai-lite',
    label: 'LXGW WenKai Lite',
    cardLabel: 'LXGW WenKai Lite',
    badge: 'Self-hosted subset',
    roles: ['readable', 'copy', 'brand'],
    acquisition: 'subset-pipeline',
    provider: null,
    familyName: 'LXGW WenKai Lite',
    fallbacks: ['"Kaiti SC"', '"STKaiti"', 'serif'],
    weights: [400],
    license: 'OFL-1.1',
    sizeHint: 'Self-hosted content subset'
  },
  {
    id: 'system-serif',
    label: 'System serif (Songti / Georgia)',
    cardLabel: 'System serif',
    badge: 'Zero download',
    roles: ['readable'],
    acquisition: 'system',
    provider: null,
    familyName: null,
    fallbacks: ['ui-serif', 'Georgia', '"Times New Roman"', '"Songti SC"', 'serif'],
    weights: [],
    license: null,
    sizeHint: 'Zero download'
  },
  {
    id: 'serif-georgia',
    label: 'System serif (Georgia)',
    cardLabel: 'Georgia',
    badge: 'Zero download',
    roles: ['brand'],
    acquisition: 'system',
    provider: null,
    familyName: null,
    fallbacks: ['Georgia', 'serif'],
    weights: [],
    license: null,
    sizeHint: 'Zero download'
  },
  {
    id: 'system-kai',
    label: 'System Kaiti (Kaiti / STKaiti)',
    cardLabel: 'System Kaiti',
    badge: 'Zero download',
    roles: ['copy'],
    acquisition: 'system',
    provider: null,
    familyName: null,
    fallbacks: ['"Kaiti SC"', '"STKaiti"', 'serif'],
    weights: [],
    license: null,
    sizeHint: 'Zero download'
  },
  {
    id: 'system-mono',
    label: 'System mono (Sarasa / SF Mono)',
    cardLabel: 'System mono',
    badge: 'Zero download',
    roles: ['mono'],
    acquisition: 'system',
    provider: null,
    familyName: null,
    fallbacks: [
      '"Sarasa Mono SC"',
      '"Noto Sans Mono CJK SC"',
      'ui-monospace',
      'SFMono-Regular',
      'Menlo',
      'Monaco',
      'Consolas',
      '"Liberation Mono"',
      '"Courier New"',
      'monospace'
    ],
    weights: [],
    license: null,
    sizeHint: 'Zero download'
  },
  {
    id: 'jetbrains-mono',
    label: 'JetBrains Mono (Latin mono)',
    cardLabel: 'JetBrains Mono',
    badge: 'Build-time download',
    roles: ['mono'],
    acquisition: 'astro-fonts-api',
    // fontsource is distributed via jsDelivr/R2 and is more reachable than fonts.google.com (unreachable on mainland networks).
    provider: 'fontsource',
    familyName: 'JetBrains Mono',
    fallbacks: [
      '"Sarasa Mono SC"',
      '"Noto Sans Mono CJK SC"',
      'ui-monospace',
      'SFMono-Regular',
      'Menlo',
      'Monaco',
      'Consolas',
      '"Liberation Mono"',
      '"Courier New"',
      'monospace'
    ],
    weights: [400],
    license: 'OFL-1.1',
    sizeHint: 'Build-time download, self-hosted (latin; CJK falls back to system mono)'
  },
  {
    id: 'noto-sans-sc',
    label: 'Noto Sans SC',
    cardLabel: 'Noto Sans SC',
    badge: 'Build-time download ~1.1MB',
    roles: ['readable', 'copy'],
    acquisition: 'astro-fonts-api',
    provider: 'fontsource',
    familyName: 'Noto Sans SC',
    fallbacks: ['"PingFang SC"', '"Microsoft YaHei"', '"Heiti SC"', 'sans-serif'],
    // Capped download cost per weight: the fontsource CJK subset is a single whole-range file (unifont does not use numbered slicing in practice),
    // so each additional weight adds ~1.1 MB to the output. Bold is synthesized by the browser, matching the single-weight strategy of lxgw-wenkai-lite.
    weights: [400],
    license: 'OFL-1.1',
    sizeHint: 'Build-time download, self-hosted (whole-range Chinese ~1.1 MB + latin 13 KB; unicode-range on-demand loading)',
    subsets: ['chinese-simplified', 'latin']
  },
  {
    id: 'fira-code',
    label: 'Fira Code (Latin mono, ligatures)',
    cardLabel: 'Fira Code',
    badge: 'Build-time download',
    roles: ['mono'],
    acquisition: 'astro-fonts-api',
    provider: 'fontsource',
    familyName: 'Fira Code',
    fallbacks: [
      '"Sarasa Mono SC"',
      '"Noto Sans Mono CJK SC"',
      'ui-monospace',
      'SFMono-Regular',
      'Menlo',
      'Monaco',
      'Consolas',
      '"Liberation Mono"',
      '"Courier New"',
      'monospace'
    ],
    weights: [400],
    license: 'OFL-1.1',
    sizeHint: 'Build-time download, self-hosted (latin; CJK falls back to system mono)'
  }
] as const satisfies readonly ThemeFontRegistryEntry[];

export type ThemeFontId = (typeof THEME_FONT_REGISTRY)[number]['id'];

/* Sole enum source for the four roles: when adding a role, only change this and the TypographyRole type; consumers always loop over this constant. */
export const TYPOGRAPHY_ROLES = ['readable', 'copy', 'mono', 'brand'] as const satisfies readonly TypographyRole[];

export const THEME_TYPOGRAPHY_DEFAULT: TypographySettings = {
  readable: 'noto-serif-sc',
  copy: 'lxgw-wenkai-lite',
  mono: 'system-mono',
  brand: 'serif-georgia'
};

export type ThemeFontOption = {
  id: ThemeFontId;
  cardLabel: string;
  badge: string;
  /* Font-family stack for card previews (see getThemeFontPreviewStack), fed directly to CSS font-family. */
  previewStack: string;
};

const entryHasRole = (entry: ThemeFontRegistryEntry, role: TypographyRole): boolean =>
  entry.roles.includes(role);

const buildRoleFontIdSet = (role: TypographyRole): ReadonlySet<string> =>
  new Set(THEME_FONT_REGISTRY.filter((entry) => entryHasRole(entry, role)).map((entry) => entry.id));

const ROLE_FONT_ID_SETS = Object.fromEntries(
  TYPOGRAPHY_ROLES.map((role) => [role, buildRoleFontIdSet(role)])
) as Record<TypographyRole, ReadonlySet<string>>;

export const isThemeFontIdForRole = (role: TypographyRole, value: string): value is ThemeFontId =>
  ROLE_FONT_ID_SETS[role].has(value);

/* Single source of truth for validation + fallback (validates after trim, returns undefined when invalid): shared by canonicalize / theme-settings /
   config-time raw parsing so the three sites don't each re-implement the same semantics. */
export const asThemeFontIdForRole = (role: TypographyRole, value: unknown): ThemeFontId | undefined => {
  const trimmed = typeof value === 'string' ? value.trim() : '';
  return isThemeFontIdForRole(role, trimmed) ? trimmed : undefined;
};

export const getThemeFontOptionsForRole = (role: TypographyRole): ThemeFontOption[] =>
  THEME_FONT_REGISTRY
    .filter((entry) => entryHasRole(entry, role))
    .map(({ id, cardLabel, badge }) => ({
      id,
      cardLabel,
      badge,
      previewStack: getThemeFontPreviewStack(id)
    }));

export const getThemeFontRegistryEntry = (id: ThemeFontId): ThemeFontRegistryEntry | undefined =>
  THEME_FONT_REGISTRY.find((entry) => entry.id === id);

/* Preview-only stack for admin cards: no var(--font-*). An unselected astro-fonts-api font has no corresponding variable on the page,
   and an undefined var() invalidates the whole font-family declaration (losing even the literal fallback), so previews always use
   literal family names + fallback and render as best they can, without downloading fonts just for the preview. */
export const getThemeFontPreviewStack = (id: ThemeFontId): string => {
  const entry = getThemeFontRegistryEntry(id);
  if (!entry) return '';
  const families = entry.familyName ? [`"${entry.familyName}"`, ...entry.fallbacks] : [...entry.fallbacks];
  return families.join(', ');
};

export const getThemeFontStack = (id: ThemeFontId): string => {
  const entry = getThemeFontRegistryEntry(id);
  if (!entry) return '';
  if (entry.acquisition === 'astro-fonts-api') {
    // The Astro Fonts API cssVariable already includes the font family and metric-aligned fallback; append the registry fallback to cover CJK glyphs.
    return [`var(--font-${entry.id})`, ...entry.fallbacks].join(', ');
  }
  return getThemeFontPreviewStack(id);
};

/* Entries in the current typography selection that require the Astro Fonts API to download at build time; astro.config and BaseLayout share this check. */
export const getSelectedAstroApiFonts = (typography: TypographySettings): ThemeFontRegistryEntry[] => {
  const selected = new Set<string>(TYPOGRAPHY_ROLES.map((role) => typography[role]));
  return THEME_FONT_REGISTRY.filter(
    (entry) => entry.acquisition === 'astro-fonts-api' && selected.has(entry.id)
  );
};

/* Lets astro.config consume a hand-read ui.json directly at config time (bypassing the full theme-settings pipeline):
   illegal/missing values always fall back to defaults, consistent with the fault tolerance of canonicalize. */
export const resolveTypographyFromRawUiSettings = (raw: unknown): TypographySettings => {
  const isRecord = (value: unknown): value is Record<string, unknown> =>
    typeof value === 'object' && value !== null && !Array.isArray(value);
  const typography = isRecord(raw) && isRecord(raw.typography) ? raw.typography : {};
  const pick = (role: TypographyRole): ThemeFontId =>
    asThemeFontIdForRole(role, typography[role]) ?? THEME_TYPOGRAPHY_DEFAULT[role];
  return { readable: pick('readable'), copy: pick('copy'), mono: pick('mono'), brand: pick('brand') };
};

/* Only emits a --font-* override for roles that deviate from the default; the default state outputs null so global.css :root tokens remain the sole default source. */
export const getTypographyStyleOverride = (typography: TypographySettings): string | null => {
  const declarations = TYPOGRAPHY_ROLES
    .filter((role) => typography[role] !== THEME_TYPOGRAPHY_DEFAULT[role])
    .map((role) => `--font-${role}: ${getThemeFontStack(typography[role])}`);
  return declarations.length ? declarations.join('; ') : null;
};
